server:
  port: ${PORT}

spring:
  application:
    name: auction-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    hostname: 3.35.210.102

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_END_POINT}
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL}

kafka:
  topic:
    bid: ${KAFKA_TOPIC_BID}
    auction-end: ${KAFKA_TOPIC_AUCTION_END}
  address: ${KAFKA_ADDRESS}

logging:
  pattern:
    level: "%5p [%X{traceId:-},  %X{spanId:-}]"
