server:
  port: ${PORT}

spring:
  application:
    name: auction-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_END_POINT}
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL}

kafka:
  topic:
    bid: ${KAFKA_TOPIC_BID}
    auction-end: ${KAFKA_TOPIC_AUCTION_END}
  address: ${KAFKA_ADDRESS}

logging:
  pattern:
    level: "%5p [%X{traceId:-},  %X{spanId:-}]"


#server:
#  port: 8012
#
#spring:
#  application:
#    name: auction-server
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/competer?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: Michew0724!
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.format_sql: true
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: httptrace, health, info, metrics, prometheus
#  tracing:
#    sampling:
#      probability: 1.0
#    propagation:
#      consume: b3
#      produce: b3_multi
#  zipkin:
#    tracing:
#      endpoint: localhost:9411
#
#kafka:
#  topic:
#    bid: bid-topic
#    auction-end: auction-end-topic
#  address: localhost:9092
#
#logging:
#  pattern:
#    level: "%5p [%X{traceId:-},  %X{spanId:-}]"